# Generated by Django 4.0.6 on 2022-08-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester', models.CharField(help_text='Requester of the translation', max_length=30, verbose_name='Requester')),
                ('received', models.DateTimeField(help_text='Translation Request Received Date and Time, as per the request email', verbose_name='Received Date & Time')),
                ('email_subject', models.CharField(help_text='Request Email Subject, without "RE" or "FW". Indicate "no subject" if the actual subject is blank.', max_length=100, verbose_name='Email Subject')),
                ('tn_no', models.CharField(blank=True, help_text='Transmittal Number as per the DCC info', max_length=50, verbose_name='Transmittal No.')),
                ('requested_date', models.DateTimeField(help_text='Date and Time when the translation is requestedto be provided back to the requester', verbose_name='Requested Date')),
                ('strict_deadline', models.BooleanField(default=False, help_text='True if the Requested Date and Time are strictlydetermined by the request. False if the Requested Date and Time are set internally.', verbose_name='Strict Deadline')),
                ('current_stage', models.CharField(choices=[('TRN', 'Translation'), ('PRF', 'Proofreading'), ('VRF', 'Verification'), ('FNL', 'Finalization'), ('SBM', 'Submitted')], help_text='Current stage of the request', max_length=3, verbose_name='Request Stage')),
                ('submitted', models.DateTimeField(blank=True, help_text='Date of submission. Not submitted yet if not indicated.', null=True, verbose_name='Submission Date')),
            ],
        ),
    ]
