# Generated by Django 4.0.6 on 2022-08-02 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the requester. Whenever possible, input first name first, and last name last.', max_length=50, verbose_name='Name')),
                ('email', models.EmailField(help_text='Email of the translation requester', max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Requester',
                'verbose_name_plural': 'Requesters',
            },
        ),
        migrations.AlterModelOptions(
            name='translationrequest',
            options={'verbose_name': 'Translation Request', 'verbose_name_plural': 'Translation Requests'},
        ),
        migrations.AddConstraint(
            model_name='requester',
            constraint=models.UniqueConstraint(fields=('name', 'email'), name='orders_requester_unique_relationships'),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='requester',
            field=models.ForeignKey(help_text='Requester of the translation', on_delete=django.db.models.deletion.RESTRICT, related_name='requests', to='orders.requester', verbose_name='Requester'),
        ),
    ]
