# Generated by Django 4.0.6 on 2022-08-03 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_add_requester_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationrequest',
            name='current_stage',
            field=models.ForeignKey(blank=True, help_text='Current stage of the request', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.requester', verbose_name='Current Stage'),
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('PRP', 'Preparation'), ('TRN', 'Translation'), ('PRF', 'Proofreading'), ('VRF', 'Verification'), ('FNL', 'Finalization')], help_text='Type of the activity from the list of pre-selected ones', max_length=3, verbose_name='Activity Type')),
                ('expected_duration', models.DurationField(blank=True, help_text='Expected duration for the activity. Default is 1 hour', null=True, verbose_name='Expected Duration')),
                ('actual_duration', models.DurationField(blank=True, help_text='Actual duration of the activity.', null=True, verbose_name='Actual Duration')),
                ('outsource', models.BooleanField()),
                ('responsible', models.ForeignKey(help_text='Registered user responsible for performing the activity', on_delete=django.db.models.deletion.RESTRICT, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Responsible')),
                ('translation_request', models.ForeignKey(help_text='Translation Request which this Activity is related to', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='orders.translationrequest', verbose_name='Translation Request')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
    ]
