# Generated by Django 4.0.6 on 2022-08-03 11:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_added_activity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationrequest',
            name='comments',
            field=models.CharField(blank=True, help_text='Comments to the Request', max_length=100, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='status',
            field=models.CharField(choices=[('NRQ', 'Not Required'), ('PND', 'Pending'), ('ONT', 'On Time'), ('ERL', 'Early'), ('LTE', 'Late')], default='PND', help_text='Translation Request status,selected from the list of the predefined ones', max_length=3, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='translationrequest',
            name='submitter',
            field=models.ForeignKey(default='', help_text='Registered user who submitted the request to the requester', on_delete=django.db.models.deletion.RESTRICT, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='Submitter'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='outsource',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
