# Generated by Django 4.0.6 on 2022-08-03 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0004_new_fields_to_translationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationrequest',
            name='current_stage',
            field=models.ForeignKey(blank=True, help_text='Current stage of the request', null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.activity', verbose_name='Current Stage'),
        ),
        migrations.AlterField(
            model_name='translationrequest',
            name='submitter',
            field=models.ForeignKey(blank=True, help_text='Registered user who submitted the request to the requester', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='Submitter'),
        ),
    ]
