# Generated by Django 4.0.6 on 2022-08-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_fix_translationrequest_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, help_text='Document Number. Leave blank if cannot be determined.', max_length=50, verbose_name='Number')),
                ('source_language', models.CharField(choices=[('EN', 'English'), ('RU', 'Russian'), ('TR', 'Turkish'), ('IT', 'Italian'), ('FR', 'French'), ('LT', 'Lithuanian'), ('UZ', 'Uzbek')], help_text='Source language of the document', max_length=2, verbose_name='Source Language')),
                ('translated_language', models.CharField(choices=[('EN', 'English'), ('RU', 'Russian'), ('TR', 'Turkish'), ('IT', 'Italian'), ('FR', 'French'), ('LT', 'Lithuanian'), ('UZ', 'Uzbek')], help_text='Language of the document after translation', max_length=2, verbose_name='Translated Language')),
                ('source_title', models.CharField(blank=True, help_text='Title of the document in the source language', max_length=200, verbose_name='Source Title')),
                ('translated_title', models.CharField(blank=True, help_text='Title of the document after translation', max_length=200, verbose_name='Translated Title')),
                ('revision', models.SmallIntegerField(blank=True, help_text='Document Revision No. ', null=True, verbose_name='Rev No.')),
                ('file_name', models.CharField(help_text='Document File Name', max_length=260, verbose_name='File Name')),
                ('file_type', models.CharField(choices=[('DOC', 'MS Word Document'), ('XLS', 'MS Excel Spreadsheet'), ('PDF', 'PDF'), ('DWG', 'AutoCAD Drawing'), ('PPT', 'MS PowerPoint Presentation'), ('MSG', 'Outlook Email message'), ('PIC', 'Picture')], help_text='Document File Type', max_length=3, verbose_name='File Type')),
                ('number_of_pages', models.SmallIntegerField(default=1, help_text='Number of physical pages subject to translation in a given document (file)', verbose_name='Number of Pages')),
                ('company', models.CharField(blank=True, help_text='Company that this document is related to', max_length=100, null=True, verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
