# Generated by Django 4.0.6 on 2022-08-04 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_document_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('PRP', 'Preparation'), ('TRN', 'Translation'), ('PRF', 'Proofreading'), ('VRF', 'Verification'), ('FNL', 'Finalization')], default='PRP', help_text='Type of the activity from the list of pre-selected ones', max_length=3, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='number_of_pages',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of physical pages subject to translation in a given document (file)', verbose_name='Number of Pages'),
        ),
        migrations.AlterField(
            model_name='document',
            name='revision',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Document Revision No. ', null=True, verbose_name='Rev No.'),
        ),
        migrations.CreateModel(
            name='Outsource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(choices=[('MTA', 'MTA')], default='MTA', help_text='Translation agency in charge of this outsourced activity', max_length=10, verbose_name='Agency')),
                ('status', models.CharField(choices=[('REQ', 'Required'), ('ONG', 'Ongoing'), ('DNE', 'Done')], default='REQ', help_text='Agency activity status', max_length=10, verbose_name='Status')),
                ('deadline', models.DateTimeField(help_text='Deadline when the agency shall provide the result', verbose_name='Deadline')),
                ('standard_pages', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount of standard pages (or "translation pages")', max_digits=5, verbose_name='Standard Pages')),
                ('dtp_cat_1', models.PositiveSmallIntegerField(default=0, help_text='Amount of DTP objects of Category 1', verbose_name='DTP Cat 1')),
                ('dtp_cat_2', models.PositiveSmallIntegerField(default=0, help_text='Amount of DTP objects of Category 2', verbose_name='DTP Cat 2')),
                ('dtp_cat_3', models.PositiveSmallIntegerField(default=0, help_text='Amount of DTP objects of Category 3', verbose_name='DTP Cat 3')),
                ('dtp_cat_4', models.PositiveSmallIntegerField(default=0, help_text='Amount of DTP objects of Category 4', verbose_name='DTP Cat 4')),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Cost of the outsourced activity in rubles', max_digits=10, verbose_name='Cost')),
                ('activity', models.OneToOneField(help_text='Activity that this Outsource is related to', on_delete=django.db.models.deletion.CASCADE, related_name='outsourced', to='orders.activity', verbose_name='Activity')),
            ],
            options={
                'verbose_name': 'Outsourced Activity',
                'verbose_name_plural': 'Outsourced Activities',
            },
        ),
        migrations.AlterField(
            model_name='activity',
            name='outsource',
            field=models.OneToOneField(blank=True, help_text='This activity will be outsourced. A corresponding Outsource shall be created.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='original_activity', to='orders.outsource', verbose_name='Outsource'),
        ),
    ]
